project:
  type: manuscript
  output-dir: docs

title: "Lab 7"
manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true



bibliography: references.bib
csl: apa.csl
